version: '3.8'

services:
  eureka-server:
    image: rheonik/chat-eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  api-gateway:
    image: rheonik/chat-apigateway-server:1.0
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - app-network
    depends_on:
      - eureka-server

networks:
  app-network:
    driver: bridge
