version: '3.8'

services:
  eureka-server:
    image: rheonik/chat-eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./config/eureka-server/application.yml:/config/application.yml
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/eureka/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  apigateway-server:
    image: rheonik/chat-apigateway-server:1.0
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./config/apigateway-server/application.yml:/config/application.yml
    networks:
      - app-network
    depends_on:
      - eureka-server

  user-service:
    image: rheonik/chat-user-service:1.0
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./config/user-service/application.yml:/config/application.yml
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
      - eureka-server

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/hyunjae/desktop/postgresql.conf:/etc/postgresql/postgresql.conf
      - /Users/hyunjae/desktop/logs/postgresql:/var/log/postgresql
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
      - /Users/hyunjae/desktop/logs/redis:/var/log/redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
