# filebeat.yml

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/spring/*.log  # Spring 애플리케이션 로그 경로
    json:
      message_key: message
      keys_under_root: true
    fields:
      service: spring-application

  - type: log
    enabled: true
    paths:
      - /var/log/kafka/*.log  # Kafka 로그 경로
    # 필요한 경우 추가 설정
    fields:
      service: kafka

  - type: log
    enabled: true
    paths:
      - /var/log/postgresql/postgresql-*.log  # PostgreSQL 로그 경로
    fields:
      service: postgresql

  - type: log
    enabled: true
    paths:
      - /var/log/redis/redis.log  # Redis 로그 경로
    fields:
      service: redis

output.logstash:
  hosts: ["logstash:5044"]
