pipeline {
    agent any

    tools {
        jdk 'JDK11'
        maven 'MAVEN_HOME'
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
        DOCKER_BUILDKIT = '1'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/hyunganom/Chatting-Application.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('eureka-server') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('eureka-server') {
                    script {
                        sh '''
                        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                        docker buildx create --use --name mybuilder || docker buildx use mybuilder
                        docker buildx build --platform linux/amd64,linux/arm64 \
                          -t rheonik/eureka-server:latest --push .
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd /home/jenkins/desktop
                docker-compose pull eureka-server
                docker-compose up -d eureka-server
                '''
            }
        }
    }
}
