pipeline {
    agent any

    tools {
        jdk 'JDK11'       // Jenkins에 설치된 JDK11 툴 이름
        maven 'MAVEN_HOME' // Jenkins에 설치된 Maven 툴 이름
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id') // Jenkins에 등록한 Docker Hub 인증 정보 ID
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/hyunganom/Chatting-Application.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('chatapp-eureka-server') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('chatapp-eureka-server') {
                    script {
                        sh '''
                        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin

                        docker build -t rheonik/eureka-server:latest .

                        docker push rheonik/eureka-server:latest
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd /home/jenkins/desktop
                docker-compose pull eureka-server
                docker-compose up -d eureka-server
                '''
            }
        }
    }
}
