spring:
  application:
    name: websocket-service
  redis:
    host: redis
    port: 6379
  cache:
    redis:
      cache-prefix: "websocket::"

  # Kafka
  kafka:
    bootstrap-servers: kafka_broker1:9092,kafka_broker2:9093,kafka_broker3:9094
    consumer:
      group-id: websocket_group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "chat.websocketserver.event, chat.messageserver.event, java.util, java.lang"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2G3H4
  access:
    expiration:
      minutes: 15
  refresh:
    expiration:
      days: 7
