apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
  namespace: chatapp
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_FILE_PATH: "/app/logs"
  application.yml: |
    spring:
      application:
        name: chat-service

      # PostgreSQL
      datasource:
        url: jdbc:postgresql://postgres:5432/chatapp_db
        username: chatuser
        password: chatpass
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

      # Redis
      redis:
        host: redis
        port: 6379

    logging:
      file:
        path: /var/log/spring
      level:
        root: INFO
        org:
          springframework.cache: DEBUG
          springframework.data.redis.cache: DEBUG
        chat.userserver.service: DEBUG

    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka/

    server:
      port: 8082
