apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: chatapp
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/chat_db"
  LOG_FILE_PATH: "/app/logs"
  application.yml: |
    spring:
      application:
        name: message-service

    server:
      port: 8083

    data:
      mongodb:
        uri: mongodb://mongo:27017/chat_db

    logging:
      file:
        path: /var/log/spring
      level:
        root: INFO
        org:
          springframework.cache: DEBUG
          springframework.data.redis.cache: DEBUG
        hyunjae.chattingapp.service: DEBUG

    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka/
