spring:
  application:
    name: message-service

  kafka:
    bootstrap-servers: kafka_broker1:9092,kafka_broker2:9093,kafka_broker3:9094
    consumer:
      group-id: "message_group_new"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

  redis:
    host: redis
    port: 6379
  cache:
    redis:
      cache-prefix: "message::"

data:
  mongodb:
    uri: mongodb://mongo:27017/chat_db

logging:
  file:
    path: /var/log/spring
  level:
    root: INFO
    org:
      springframework.cache: DEBUG
      springframework.data.redis.cache: DEBUG
    hyunjae.chattingapp.service: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
