spring:
  application:
    name: chat-service
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://postgres:5432/chatapp_db
    username: chatuser
    password: chatpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis
  redis:
    host: redis
    port: 6379
  cache:
    redis:
      cache-prefix: "chat::"
  kafka:
    bootstrap-servers: kafka_broker1:9092,kafka_broker2:9093,kafka_broker3:9094
    consumer:
      group-id: "chat_group"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  file:
    path: /var/log/spring
  level:
    root: INFO
    org:
      springframework.cache: DEBUG
      springframework.data.redis.cache: DEBUG
    chat.userserver.service: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8082
