spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/chatapp_db?sslmode=disable
    username: chatuser
    password: chatpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis
  redis:
    host: redis
    port: 6379
  cache:
    redis:
      cache-prefix: "user::"
  kafka:
    bootstrap-servers: kafka_broker1:9092,kafka_broker2:9093,kafka_broker3:9094
    consumer:
      group-id: "user_group"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  file:
    path: /var/log/spring
  level:
    root: INFO
    org:
      springframework.cache: DEBUG
      springframework.data.redis.cache: DEBUG
    chat.userserver.service: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8081
