apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: chatapp
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: rheonik/chat-chat-service:1.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: SPRING_PROFILES_ACTIVE
            - name: LOG_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: LOG_FILE_PATH
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: config-volume
          configMap:
            name: chat-service-config
        - name: logs-volume
          emptyDir: {}
