apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: chatapp
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: rheonik/chat-message-service:1.0
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SPRING_DATA_MONGODB_URI
            - name: LOG_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: LOG_FILE_PATH
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          emptyDir: {}
