apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "chatuser"
            - name: POSTGRES_PASSWORD
              value: "chatpass"
            - name: POSTGRES_DB
              value: "chatapp_db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-conf
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgres-logs
              mountPath: /var/log/postgresql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-conf
          configMap:
            name: postgres-config
        - name: postgres-logs
          hostPath:
            path: /Users/hyunjae/desktop/logs/postgresql
            type: Directory
