apiVersion: v1
kind: Service
metadata:
  name: apigateway-server
  namespace: chatapp
spec:
  selector:
    app: apigateway-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # 외부 접근을 위해 NodePort 설정
