apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chatapp
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
