apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: chatapp
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
