apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: chatapp
spec:
  selector:
    app: websocket-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
